name: Test tools
on: ["pull_request"]
jobs:
  test_tools:
    runs-on: ${{ matrix.os }}
    strategy:
      # We only need to run tools with a single python version.  Ideally
      # this will be the latest version of python used in the action.
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11"]
    steps:
    ##-- General Setup Steps
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build & install packages
      run: |
        pushd mytemplate_pypkg
        python setup.py sdist
        pushd dist && pip install $(ls mytemplate-*.tar.gz) && popd
        popd
        pushd mytemplate2_pypkg
        python setup.py sdist
        pushd dist && pip install $(ls mytemplate2-*.tar.gz) && popd
        popd
        pip list

    ##-- Run all tools at least once
    - name: Exercise all tools
      run: |
        # check_python_code.sh is being used in the Flake8 action.
        ./tools/test_mytemplate_installation.py
        ./tools/test_mytemplate2_installation.py
