name: Check python with Flake8
on: ["pull_request"]
jobs:
  flake8:
    runs-on: ${{ matrix.os }}
    strategy:
      # We only need to check style with a single python version & OS
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]
    steps:
    ##-- General Setup Steps
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup python with tox
      run: ./.github/workflows/setup_tox_github_action.sh

    ##-- Test Execution Step
    - name: Check all python packages
      run: |
        # Let each python package dictate how to check code
        pushd mytemplate_pypkg && tox -r -e py-check && popd
        pushd mytemplate2_pypkg && tox -r -e py-check && popd
        # Load up a virtual env to access flake8 ...
        pushd mytemplate_pypkg && . ./.tox/check/bin/activate && pushd
        # and check all other python in repo manually
        pushd tools && flake8 && popd
